/**
 * Product code master data (16-char SAPL code: Discipline 1 + Category 1 + Details 4 + Free 4 + Free 4 + Free 2).
 * GENERATED from "Product Code Generator/master_data.py" by export_master_ts.py - edit that file, not this one.
 * Item order matters: when two items match at the same position, the earlier one wins.
 * Rule syntax (size / spec / free3): see master_data.py.
 */

export type ItemDef = { code: string; name: string; cat: string; hsn: string; re: RegExp; size: string; spec: string; free3: string };

/** 1st character - fixed list from SAPL_CRM "Create Line Item". */
export const DISCIPLINES: { code: string; name: string }[] = [
  { code: "A", name: "Air Conditioning" },
  { code: "E", name: "Electrical" },
  { code: "F", name: "Fire Fighting" },
  { code: "P", name: "Plumbing & Drainage" },
  { code: "C", name: "Civil" },
  { code: "X", name: "Extra Low Voltage (ELV)" },
  { code: "B", name: "BMS" },
];

/** 2nd character - fixed list from SAPL_CRM. `text` is the OMC category column. */
export const CATEGORIES: { code: string; name: string; text: string }[] = [
  { code: "E", name: "Equipment", text: "EQUIPMENTS" },
  { code: "G", name: "General", text: "GENERAL" },
  { code: "L", name: "Labour", text: "LABOUR" },
  { code: "R", name: "Rental", text: "RENTAL" },
  { code: "S", name: "Service", text: "SERVICE" },
  { code: "F", name: "Scaffolding", text: "SCAFFOLDING" },
  { code: "A", name: "Accessories", text: "ACCESSORIES" },
  { code: "P", name: "PMC", text: "PMC" },
  { code: "C", name: "Consumables", text: "CONSUMABLES" },
  { code: "T", name: "Transport", text: "TRANSPORT" },
  { code: "M", name: "Material", text: "MATERIAL" },
  { code: "D", name: "Ducting", text: "DUCTING" },
];

/** Free-field conventions (from the SAPL legend and issued OMC codes). */
export const FREE_FIELD_EXAMPLES: [string, string][] = [
  ["4500", "4500 CFM"], ["12KC", "12000 CFM"], ["10K5", "10500 CFM"], ["450X", "450 CFM"], ["900X", "900 USGPM flow"], ["3TRX", "3 TR"], ["2P5T", "2.5 TR"], ["75TR", "75 TR"], ["34HP", "34 HP"], ["15KW", "15 KW"], ["5P5W", "5.5 KW"], ["0P15", "0.15 KW"], ["150M", "150 MM dia"], ["25MM", "25 MM dia"], ["9MMX", "9 MM thick"], ["24GX", "24 gauge"], ["3C16", "3 core x 16 sq.mm"], ["2503", "25 x 3 mm strip"], ["SC40", "Schedule 40"], ["CLBX", "Class B"], ["64AI", "64 Amps"], ["12WD", "12 Way DB"], ["WINS", "With insulation"], ["PN16", "PN16 rating"], ["TRNC", "Trench"], ["PCOA", "Protective coating"], ["FRLS", "Flame retardant low smoke"], ["FRTD", "Fire rated"], ["SSKN", "Single skin"], ["SUPL", "Supply air"], ["30", "Free Field 3: 30 mm static pressure (fans)"], ["XX", "Free Field 3: generic"],
];

/** Free Field 2 keywords, searched top to bottom by ATTR. */
export const SPECS: { code: string; name: string; re: RegExp }[] = [
  { code: "FRLS", name: "Flame Retardant Low Smoke", re: new RegExp("\\bfrls\\b", "i") },
  { code: "TRNC", name: "Trench", re: new RegExp("trench", "i") },
  { code: "STPX", name: "For STP", re: new RegExp("for stp\\b", "i") },
  { code: "WINS", name: "With Insulation", re: new RegExp("\\binsulated\\b|with insulation|shall be insulated", "i") },
  { code: "PCOA", name: "Protective Coating", re: new RegExp("protective coating", "i") },
  { code: "NITR", name: "Nitrile Rubber", re: new RegExp("nitrile", "i") },
  { code: "XLPE", name: "XLPE Insulation", re: new RegExp("\\bxlpe\\b|cross.?linked", "i") },
  { code: "ELAS", name: "Elastomeric", re: new RegExp("elastomeric", "i") },
  { code: "RKWL", name: "Rock Wool", re: new RegExp("rock ?wool", "i") },
  { code: "ARMD", name: "Armoured", re: new RegExp("\\barmou?red\\b|\\bar\\.\\s*cable", "i") },
  { code: "UNSC", name: "Unscreened", re: new RegExp("un-?screened|unshielded", "i") },
  { code: "SHLD", name: "Shielded", re: new RegExp("shield|sheiled|screened", "i") },
  { code: "PN25", name: "PN25 Rating", re: new RegExp("\\bpn ?25\\b", "i") },
  { code: "PN16", name: "PN16 Rating", re: new RegExp("\\bpn ?16\\b|16 kg/sq", "i") },
  { code: "PN10", name: "PN10 Rating", re: new RegExp("\\bpn ?10\\b", "i") },
  { code: "GLYC", name: "Glycerine Filled", re: new RegExp("glycerine", "i") },
  { code: "SSKN", name: "Single Skin", re: new RegExp("single skin", "i") },
  { code: "FRTD", name: "Fire Rated", re: new RegExp("fire rated|fire damper|smoke and fire|\\bul ?555", "i") },
  { code: "SUPL", name: "Supply Air", re: new RegExp("supply air", "i") },
  { code: "RETN", name: "Return Air", re: new RegExp("return air", "i") },
  { code: "EXHT", name: "Exhaust Air", re: new RegExp("exhaust air", "i") },
  { code: "SFLP", name: "Single Flap", re: new RegExp("single flap", "i") },
  { code: "ALPC", name: "Powder Coated GI", re: new RegExp("powder coat", "i") },
  { code: "HDGL", name: "Hot Dip Galvanised", re: new RegExp("hot dip", "i") },
  { code: "R410", name: "R-410A Refrigerant", re: new RegExp("r-?410", "i") },
  { code: "R32X", name: "R-32 Refrigerant", re: new RegExp("\\br-?32\\b", "i") },
  { code: "4WAY", name: "4-Way", re: new RegExp("4.?way|four way", "i") },
  { code: "IP54", name: "IP54 Rating", re: new RegExp("\\bip ?54\\b", "i") },
  { code: "IP21", name: "IP21 Protection", re: new RegExp("\\bip ?21\\b", "i") },
  { code: "MODB", name: "Modbus Protocol", re: new RegExp("modbus", "i") },
  { code: "WCO2", name: "With CO2 Monitoring", re: new RegExp("co2 mo", "i") },
  { code: "CTWR", name: "Cooling Tower", re: new RegExp("cooling tower", "i") },
  { code: "VRFO", name: "VRF Outdoor Unit", re: new RegExp("vrf outdoor|outdoor units?", "i") },
  { code: "FUME", name: "Fume Exhaust", re: new RegExp("\\bfume", "i") },
  { code: "EXPS", name: "Exposed", re: new RegExp("exposed", "i") },
  { code: "PAST", name: "Paste", re: new RegExp("paste", "i") },
  { code: "UPVC", name: "Rigid uPVC", re: new RegExp("\\bu?pvc\\b", "i") },
  { code: "ERTH", name: "Earthing", re: new RegExp("earthing", "i") },
  { code: "SSXX", name: "Stainless Steel", re: new RegExp("stainless|\\bss\\b", "i") },
  { code: "CUXX", name: "Copper", re: new RegExp("copper", "i") },
  { code: "ALUM", name: "Aluminium", re: new RegExp("alumin|\\bal\\b\\.?", "i") },
  { code: "GIXX", name: "Galvanised Iron", re: new RegExp("\\bg\\.?i\\.?\\b|galvani", "i") },
];

export const ITEMS: ItemDef[] = [
  { code: "CWPX", name: "Condenser Water Pump", cat: "E", hsn: "84137010", re: new RegExp("condenser (water )?pump", "i"), size: "USGPM", spec: "MOTORKW", free3: "" },
  { code: "VPCP", name: "Variable Primary Chilled Water Pump", cat: "E", hsn: "84137010", re: new RegExp("(variable primary|chilled water) pump|vertical inline", "i"), size: "FIX:VILN", spec: "NONE", free3: "" },
  { code: "FFPU", name: "Fire Fighting Pump", cat: "E", hsn: "84137010", re: new RegExp("fire (fighting )?pump|jockey pump|hydrant pump|sprinkler pump", "i"), size: "USGPM", spec: "MOTORKW", free3: "" },
  { code: "CHIL", name: "Chiller", cat: "E", hsn: "84186990", re: new RegExp("\\bchiller\\b(?! water)", "i"), size: "TR", spec: "NONE", free3: "" },
  { code: "AHUC", name: "AHU Chilled Water Type", cat: "E", hsn: "84151090", re: new RegExp("air handling units? for chilled water|chilled water (type )?(ahu|air handling)", "i"), size: "TR", spec: "CFM", free3: "" },
  { code: "AHUD", name: "AHU DX Type", cat: "E", hsn: "84151090", re: new RegExp("air handling units? for (vrf|dx)|\\bdx (type )?(ahu|air handling)", "i"), size: "TR", spec: "CFM", free3: "" },
  { code: "CSUX", name: "Ceiling Suspended Unit", cat: "E", hsn: "84151090", re: new RegExp("ceiling suspended (air handling )?units?", "i"), size: "TR", spec: "CFM", free3: "ESP" },
  { code: "AHUX", name: "Air Handling Unit", cat: "E", hsn: "84151090", re: new RegExp("air handling unit", "i"), size: "TR", spec: "CFM", free3: "" },
  { code: "FCUX", name: "Fan Coil Unit", cat: "E", hsn: "84151090", re: new RegExp("fan coil unit|\\bfcu\\b", "i"), size: "TR", spec: "CFM", free3: "" },
  { code: "CWCS", name: "Chilled Water Cassette Unit", cat: "E", hsn: "84151090", re: new RegExp("chilled water cassette", "i"), size: "TR", spec: "NONE", free3: "" },
  { code: "VCAS", name: "VRF Cassette Unit", cat: "E", hsn: "84159000", re: new RegExp("vrf cassette|cassette unit", "i"), size: "TR", spec: "@4WAY", free3: "" },
  { code: "VHWU", name: "VRF Hi-Wall Unit", cat: "E", hsn: "84151010", re: new RegExp("hi[ -]?wall", "i"), size: "TR", spec: "NONE", free3: "" },
  { code: "VRFO", name: "VRF Outdoor Unit", cat: "E", hsn: "84159000", re: new RegExp("vrf outdoor|vrf odu|vrf unit|outdoor unit(?! stand)", "i"), size: "HP", spec: "@R410|@R32X", free3: "" },
  { code: "VKIT", name: "VRF AHU Kit", cat: "A", hsn: "84158290", re: new RegExp("vrf ahu kit|ahu kit", "i"), size: "HP", spec: "CFM", free3: "" },
  { code: "DSPJ", name: "Double Skin Plenum with Jet Nozzles", cat: "A", hsn: "73089090", re: new RegExp("plenum with jet nozzle", "i"), size: "TR", spec: "CFM", free3: "" },
  { code: "FCEU", name: "Floor Mounted Cabinet Exhaust Unit", cat: "E", hsn: "84145930", re: new RegExp("floor mounted cabinet|cabinet type (exhaust|fresh air) units?", "i"), size: "CFM", spec: "NONE", free3: "ESP" },
  { code: "RIEF", name: "Rectangular Inline Exhaust Fan", cat: "E", hsn: "84149040", re: new RegExp("inline exhaust (air )?fan|rectangular type inline", "i"), size: "CFM", spec: "NONE", free3: "ESP" },
  { code: "WMPF", name: "Wall Mounted Propeller Fan", cat: "E", hsn: "84145990", re: new RegExp("wall mounted propeller|propeller (type |exhaust )?fans?", "i"), size: "CFM", spec: "ESPMM", free3: "" },
  { code: "INFN", name: "Inline Fan", cat: "E", hsn: "84145990", re: new RegExp("inline fan|box type inline|cabinet type inline", "i"), size: "CFM", spec: "NONE", free3: "ESP" },
  { code: "BFFN", name: "Bifurcated Fan", cat: "E", hsn: "84145990", re: new RegExp("bi-?furcated", "i"), size: "CFM", spec: "NONE", free3: "ESP" },
  { code: "SWFN", name: "SISW Fan", cat: "E", hsn: "84145990", re: new RegExp("sisw fan", "i"), size: "CFM", spec: "NONE", free3: "ESP" },
  { code: "DWFN", name: "DIDW Cabinet Fan", cat: "E", hsn: "84145990", re: new RegExp("didw fan|cabinet fan", "i"), size: "CFM", spec: "NONE", free3: "ESP" },
  { code: "VNFN", name: "Ventilation Fan", cat: "E", hsn: "84145990", re: new RegExp("ventilation fan|exhaust fan|axial fan|jet fan", "i"), size: "CFM", spec: "NONE", free3: "ESP" },
  { code: "FVAV", name: "Flat Oval VAV", cat: "E", hsn: "90328990", re: new RegExp("flat oval vav", "i"), size: "CFM", spec: "FIX:CFMX", free3: "" },
  { code: "RVAV", name: "Rectangular VAV", cat: "E", hsn: "90328990", re: new RegExp("rectangular vav", "i"), size: "CFM", spec: "FIX:CFMX", free3: "" },
  { code: "VFDP", name: "VFD By-pass Panel", cat: "E", hsn: "85371000", re: new RegExp("variable frequency drive by ?-?pass|vfd by ?-?pass|by ?-?pass starter", "i"), size: "KW", spec: "@CTWR", free3: "" },
  { code: "VFDX", name: "Variable Frequency Drive", cat: "E", hsn: "85044090", re: new RegExp("variable frequency drive starter panel|vfd starter panel|\\bvfd\\b", "i"), size: "KW", spec: "NONE", free3: "" },
  { code: "SDSP", name: "Star Delta Starter Panel", cat: "A", hsn: "85369090", re: new RegExp("star delta starter", "i"), size: "KW", spec: "NONE", free3: "" },
  { code: "DOLP", name: "DOL Starter Panel", cat: "A", hsn: "85369090", re: new RegExp("\\bdol starter|direct on line starter", "i"), size: "KW", spec: "FIX:KWXX", free3: "" },
  { code: "LCPN", name: "Logical Control Panel", cat: "A", hsn: "85371000", re: new RegExp("logical control panel|pump logic", "i"), size: "KW", spec: "NONE", free3: "" },
  { code: "STPN", name: "Starter Panel", cat: "A", hsn: "85371000", re: new RegExp("starter panel", "i"), size: "KW", spec: "NONE", free3: "" },
  { code: "FDCP", name: "Fire Damper Control Panel", cat: "A", hsn: "85371000", re: new RegExp("control panel for (fire|moto)|actuators? control panel|fire damper control panel", "i"), size: "COUNT", spec: "NONE", free3: "" },
  { code: "CTPN", name: "Control Panel", cat: "A", hsn: "85371000", re: new RegExp("control panel", "i"), size: "NONE", spec: "NONE", free3: "" },
  { code: "RPBS", name: "Remote Push Button Station", cat: "A", hsn: "85369090", re: new RegExp("push button station", "i"), size: "@IP54", spec: "NONE", free3: "" },
  { code: "ISOL", name: "Isolator", cat: "A", hsn: "85365090", re: new RegExp("\\bisolators?\\b", "i"), size: "@VRFO", spec: "NONE", free3: "" },
  { code: "TBOX", name: "Terminal Box", cat: "A", hsn: "85369030", re: new RegExp("terminal box", "i"), size: "NONE", spec: "NONE", free3: "" },
  { code: "SRAC", name: "Spring Return Actuator", cat: "A", hsn: "85014010", re: new RegExp("spring return actuator|\\bactuator\\b", "i"), size: "TORQUE", spec: "NONE", free3: "" },
  { code: "DDCC", name: "DDC Controller", cat: "A", hsn: "90328990", re: new RegExp("ddc controller|direct digital controller", "i"), size: "NONE", spec: "NONE", free3: "" },
  { code: "VRFI", name: "VRF Integrator", cat: "A", hsn: "90328990", re: new RegExp("vrf integrator", "i"), size: "NONE", spec: "NONE", free3: "" },
  { code: "CNCT", name: "Central Controller", cat: "A", hsn: "84159000", re: new RegExp("central controller|cente?ral remote", "i"), size: "NONE", spec: "NONE", free3: "" },
  { code: "ASQC", name: "Auto Sequencing Controller", cat: "A", hsn: "90328990", re: new RegExp("auto sequencing", "i"), size: "NONE", spec: "NONE", free3: "" },
  { code: "BMSC", name: "BMS Connectivity", cat: "A", hsn: "90328990", re: new RegExp("bms connectivity|software & hardware|interface or integrator|vav integrator|interface unit", "i"), size: "NONE", spec: "NONE", free3: "" },
  { code: "SWLC", name: "Software & License", cat: "S", hsn: "", re: new RegExp("software", "i"), size: "NONE", spec: "NONE", free3: "" },
  { code: "VAVC", name: "VAV Installation & Commissioning", cat: "S", hsn: "", re: new RegExp("commissioning of\\s+vav units with thermostat", "i"), size: "NONE", spec: "NONE", free3: "" },
  { code: "BTMC", name: "BTU Meter Cable", cat: "A", hsn: "85446090", re: new RegExp("btu meter cable", "i"), size: "CABLE", spec: "ATTR", free3: "" },
  { code: "BTUM", name: "BTU Meter", cat: "A", hsn: "90261010", re: new RegExp("btu meter", "i"), size: "DIA|MM", spec: "FIX:WINS", free3: "" },
  { code: "PRES", name: "Pressure Sensor", cat: "A", hsn: "90262090", re: new RegExp("pressure sensor", "i"), size: "FIX:SENS", spec: "NONE", free3: "" },
  { code: "CSEN", name: "CO2 Sensor", cat: "A", hsn: "90258090", re: new RegExp("co2 sensor", "i"), size: "NONE", spec: "NONE", free3: "" },
  { code: "IAQS", name: "IAQ Sensor", cat: "A", hsn: "90262000", re: new RegExp("iaq sensor", "i"), size: "NONE", spec: "NONE", free3: "" },
  { code: "H2SN", name: "Hydrogen Sensor", cat: "A", hsn: "90271000", re: new RegExp("hydrogen sensor", "i"), size: "NONE", spec: "NONE", free3: "" },
  { code: "WLSN", name: "Water Leak Sensor", cat: "A", hsn: "85311090", re: new RegExp("water leak", "i"), size: "NONE", spec: "NONE", free3: "" },
  { code: "AVTS", name: "Air Velocity Transmitter", cat: "A", hsn: "90261090", re: new RegExp("air velocity", "i"), size: "NONE", spec: "NONE", free3: "" },
  { code: "THDU", name: "Temperature & RH Display", cat: "A", hsn: "90251990", re: new RegExp("temperature & rh|rh display", "i"), size: "NONE", spec: "NONE", free3: "" },
  { code: "THST", name: "Thermostat (Energy Saving)", cat: "A", hsn: "90258090", re: new RegExp("energy saving.{0,40}thermostat", "i"), size: "@MODB", spec: "@IP21", free3: "" },
  { code: "THRM", name: "Thermostat", cat: "A", hsn: "90251190", re: new RegExp("thermostat", "i"), size: "@WCO2", spec: "NONE", free3: "" },
  { code: "TMGG", name: "Temperature Gauge", cat: "A", hsn: "90262000", re: new RegExp("temperature gauge|thermometer", "i"), size: "DIA|MM", spec: "@PN16", free3: "" },
  { code: "THMW", name: "Thermowell", cat: "A", hsn: "90251190", re: new RegExp("thermowell", "i"), size: "NONE", spec: "@PN16", free3: "" },
  { code: "TPMI", name: "Test Point Measuring Instrument", cat: "A", hsn: "90262000", re: new RegExp("test point measuring", "i"), size: "NONE", spec: "@PN16", free3: "" },
  { code: "TSTP", name: "Test Point", cat: "A", hsn: "84819090", re: new RegExp("test points?", "i"), size: "NONE", spec: "@PN16", free3: "" },
  { code: "PRGG", name: "Pressure Gauge", cat: "A", hsn: "90262000", re: new RegExp("pressure g(au|ua)ges?", "i"), size: "DIA|MM", spec: "@GLYC|@PN16", free3: "" },
  { code: "MSFD", name: "Motorized Smoke and Fire Damper", cat: "A", hsn: "73089090", re: new RegExp("(smoke and fire damper|ul ?555|motori[sz]ed fire damper)s?(?!\\s*(on/off )?actuator)", "i"), size: "GAUGE", spec: "FIX:FRTD", free3: "" },
  { code: "FDFL", name: "Fire Damper Fusible Link", cat: "A", hsn: "73089090", re: new RegExp("fusible link|fire damper(?!\\s*(on/off )?actuator|\\s*control)", "i"), size: "GAUGE", spec: "FIX:FRTD", free3: "" },
  { code: "MVCD", name: "Motorized Volume Control Damper", cat: "A", hsn: "73089090", re: new RegExp("motori[sz]ed volume control", "i"), size: "GAUGE", spec: "NONE", free3: "" },
  { code: "VCOD", name: "Volume Control Opposed Damper", cat: "A", hsn: "73089090", re: new RegExp("(volume control (opposed blade )?damper.{0,20}flat oval|flat oval volume control)", "i"), size: "FIX:FLOV", spec: "GAUGE", free3: "" },
  { code: "VCOD", name: "Volume Control Opposed Damper", cat: "A", hsn: "73089090", re: new RegExp("volume control (opposed blade )?damper", "i"), size: "GAUGE", spec: "NONE", free3: "" },
  { code: "CLDP", name: "Collar Damper", cat: "A", hsn: "76169990", re: new RegExp("collar damper", "i"), size: "NONE", spec: "NONE", free3: "" },
  { code: "BKDD", name: "Back Draft Damper", cat: "A", hsn: "73089090", re: new RegExp("back ?draft damper", "i"), size: "GAUGE", spec: "NONE", free3: "" },
  { code: "SSDP", name: "Stream Splitter Damper", cat: "A", hsn: "76169990", re: new RegExp("splitter damper", "i"), size: "NONE", spec: "NONE", free3: "" },
  { code: "HMDM", name: "Hit & Miss Damper", cat: "A", hsn: "76169990", re: new RegExp("hit+ ?& ?miss", "i"), size: "@ALUM", spec: "NONE", free3: "" },
  { code: "NRDP", name: "Non Return Damper", cat: "A", hsn: "73089090", re: new RegExp("non return damper", "i"), size: "NONE", spec: "NONE", free3: "" },
  { code: "SPBD", name: "Spigot with Butterfly Damper", cat: "A", hsn: "73089090", re: new RegExp("spigots?|spicot", "i"), size: "DIA|MM", spec: "@SFLP", free3: "" },
  { code: "GRCL", name: "GI Round Collar", cat: "A", hsn: "73089090", re: new RegExp("round collar", "i"), size: "DIA|MM", spec: "NONE", free3: "" },
  { code: "RFDC", name: "Round Flexible Duct", cat: "A", hsn: "83079000", re: new RegExp("flexible ducts?", "i"), size: "DIA|MM", spec: "@WINS", free3: "" },
  { code: "SDAT", name: "Sound Attenuator", cat: "A", hsn: "73089090", re: new RegExp("attenuator", "i"), size: "GAUGE", spec: "NONE", free3: "" },
  { code: "CTSL", name: "Cross Talk Silencer", cat: "A", hsn: "73089090", re: new RegExp("cross talk", "i"), size: "NONE", spec: "NONE", free3: "" },
  { code: "CANV", name: "Canvas", cat: "A", hsn: "39173990", re: new RegExp("canvas", "i"), size: "NONE", spec: "NONE", free3: "" },
  { code: "SAPB", name: "Spill Air Plenum Box", cat: "A", hsn: "73089090", re: new RegExp("spill air plenum|plenum box", "i"), size: "SQDIM", spec: "@WINS", free3: "" },
  { code: "DSPL", name: "Double Skin Plenum", cat: "A", hsn: "73089090", re: new RegExp("plenum", "i"), size: "NONE", spec: "NONE", free3: "" },
  { code: "JTNZ", name: "Jet Nozzles", cat: "A", hsn: "76169990", re: new RegExp("jet nozzles?", "i"), size: "DIA|MM", spec: "NONE", free3: "" },
  { code: "SLDF", name: "Slot Diffuser", cat: "A", hsn: "76169990", re: new RegExp("slot(ted)? diffuser|\\d\\s*slot\\b", "i"), size: "SLOT", spec: "NONE", free3: "" },
  { code: "RNDF", name: "Round Diffuser", cat: "A", hsn: "76169990", re: new RegExp("round diffuser", "i"), size: "DIA|MM", spec: "@SUPL!|@RETN!", free3: "" },
  { code: "SQDF", name: "Square Diffuser", cat: "A", hsn: "76169990", re: new RegExp("square diffuser", "i"), size: "SQDIM", spec: "@SUPL!|@RETN!", free3: "" },
  { code: "EGGC", name: "Egg Crate Grilles", cat: "A", hsn: "76169990", re: new RegExp("egg ?crate", "i"), size: "NONE", spec: "NONE", free3: "" },
  { code: "CVGR", name: "Curved Grilles", cat: "A", hsn: "76169990", re: new RegExp("curved grille", "i"), size: "NONE", spec: "NONE", free3: "" },
  { code: "LNGR", name: "Linear Grilles", cat: "A", hsn: "76169990", re: new RegExp("linear grill", "i"), size: "NONE", spec: "NONE", free3: "" },
  { code: "GRLS", name: "Grilles", cat: "A", hsn: "76169990", re: new RegExp("\\bgrill(e)?s?\\b", "i"), size: "NONE", spec: "@SUPL!|@RETN!|@EXHT!", free3: "" },
  { code: "DRML", name: "Drum Louvers", cat: "A", hsn: "76169990", re: new RegExp("drum louv", "i"), size: "NONE", spec: "NONE", free3: "" },
  { code: "DRLV", name: "Door Louver", cat: "A", hsn: "76169990", re: new RegExp("door louv", "i"), size: "NONE", spec: "NONE", free3: "" },
  { code: "LOUV", name: "Louvers", cat: "A", hsn: "73089090", re: new RegExp("louv(er|re)s?", "i"), size: "@ALUM", spec: "NONE", free3: "" },
  { code: "EXDV", name: "Exhaust Disc Valve", cat: "A", hsn: "73089090", re: new RegExp("disc valve", "i"), size: "DIA|MM", spec: "NONE", free3: "" },
  { code: "BWRM", name: "Bird Wire Mesh", cat: "A", hsn: "73141410", re: new RegExp("bird (wire )?mesh|bird screen", "i"), size: "GAUGE", spec: "NONE", free3: "" },
  { code: "WTHD", name: "Weather Hood", cat: "A", hsn: "84159000", re: new RegExp("weather hood", "i"), size: "NONE", spec: "NONE", free3: "" },
  { code: "ACDR", name: "Duct Access Door", cat: "A", hsn: "73089090", re: new RegExp("access door", "i"), size: "NONE", spec: "ATTR", free3: "" },
  { code: "FRPD", name: "FRP Duct", cat: "A", hsn: "73089090", re: new RegExp("frp duct", "i"), size: "@FUME", spec: "NONE", free3: "" },
  { code: "ARBL", name: "Air Balancing", cat: "L", hsn: "", re: new RegExp("air balancing|testing, adjusting and balancing|\\btab works", "i"), size: "FIX:HVAC", spec: "NONE", free3: "" },
  { code: "WTRB", name: "Water Balancing", cat: "L", hsn: "", re: new RegExp("water balancing|water network balancing", "i"), size: "FIX:HVAC", spec: "NONE", free3: "" },
  { code: "MSFX", name: "MS Supporting Works", cat: "L", hsn: "72161000", re: new RegExp("supporting works|ms supports? for", "i"), size: "FIX:SSUP", spec: "FIX:WPNT", free3: "" },
  { code: "MSSX", name: "MS Structural Works", cat: "L", hsn: "72161000", re: new RegExp("ms structural|mild steel structural", "i"), size: "FIX:STRC", spec: "NONE", free3: "" },
  { code: "MPST", name: "Pressure Testing", cat: "A", hsn: "", re: new RegExp("pressure testing", "i"), size: "NONE", spec: "FIX:TEST", free3: "" },
  { code: "GASC", name: "Gas Charging", cat: "A", hsn: "", re: new RegExp("gas charging", "i"), size: "NONE", spec: "NONE", free3: "" },
  { code: "IAQT", name: "Indoor Air Quality Test", cat: "A", hsn: "", re: new RegExp("iaq test|indoor air quality test", "i"), size: "NONE", spec: "NONE", free3: "" },
  { code: "CMLS", name: "Commissioning, Lifting & Shifting", cat: "A", hsn: "", re: new RegExp("lifting (and|&) shifting", "i"), size: "NONE", spec: "NONE", free3: "" },
  { code: "DSMT", name: "Dismantling of Existing Works", cat: "S", hsn: "", re: new RegExp("removing of existing|dismantling", "i"), size: "NONE", spec: "NONE", free3: "" },
  { code: "WRPP", name: "Wrapping and Painting", cat: "A", hsn: "", re: new RegExp("wrapping (and|&) painting", "i"), size: "NONE", spec: "NONE", free3: "" },
  { code: "PNTG", name: "Painting", cat: "A", hsn: "", re: new RegExp("painting of|\\bpainting\\b", "i"), size: "@EXPS", spec: "NONE", free3: "" },
  { code: "WRRS", name: "Wire Rope Support", cat: "A", hsn: "73181900", re: new RegExp("wire rope", "i"), size: "NONE", spec: "NONE", free3: "" },
  { code: "NPGS", name: "Neoprene Gasket", cat: "A", hsn: "39199020", re: new RegExp("neoprene gasket", "i"), size: "NONE", spec: "NONE", free3: "" },
  { code: "CONE", name: "Cone Piece", cat: "A", hsn: "73089090", re: new RegExp("cone piece", "i"), size: "NONE", spec: "NONE", free3: "" },
  { code: "ADHR", name: "Adhesive", cat: "A", hsn: "35069999", re: new RegExp("adhe?s?ive", "i"), size: "NONE", spec: "@PAST", free3: "" },
  { code: "FSLT", name: "Fire Sealants", cat: "A", hsn: "32141000", re: new RegExp("fire (rated )?seal(ant|ing)|fire barrier mortar", "i"), size: "THK", spec: "FIX:FRTD", free3: "" },
  { code: "FRWP", name: "Duct Fire Wrap", cat: "A", hsn: "68069000", re: new RegExp("fire wrap", "i"), size: "NONE", spec: "NONE", free3: "" },
  { code: "INSU", name: "Insulation", cat: "A", hsn: "40091100", re: new RegExp("wall acoustic insulation|insulation applied inside of ahu room|ahu room wall", "i"), size: "FIX:ACOU", spec: "FIX:WALL", free3: "" },
  { code: "AINS", name: "Acoustic Insulation", cat: "A", hsn: "70199090", re: new RegExp("acoustic insulation of ducts?|duct acoustic insulation|acoustic lining", "i"), size: "THK", spec: "NONE", free3: "" },
  { code: "UDIN", name: "Underdeck Insulation", cat: "A", hsn: "40081110", re: new RegExp("under ?deck insulation", "i"), size: "THK", spec: "@ELAS", free3: "" },
  { code: "THIN", name: "Thermal Insulation", cat: "A", hsn: "40081110", re: new RegExp("thermal insulation", "i"), size: "THK", spec: "@XLPE|@NITR", free3: "" },
  { code: "PRIP", name: "Pre-Insulated Pipe", cat: "A", hsn: "73089090", re: new RegExp("pre-?insulated pipe", "i"), size: "DIA|MM", spec: "INSTHK", free3: "" },
  { code: "ALCL", name: "Aluminium Cladding", cat: "A", hsn: "76061200", re: new RegExp("cladding", "i"), size: "GAUGE", spec: "NONE", free3: "" },
  { code: "INBL", name: "Inertia Block", cat: "A", hsn: "", re: new RegExp("inertia block|inetria block", "i"), size: "NONE", spec: "NONE", free3: "" },
  { code: "SPIS", name: "Spring Isolator", cat: "A", hsn: "85369090", re: new RegExp("spring isolator", "i"), size: "NONE", spec: "NONE", free3: "" },
  { code: "CHWP", name: "Chilled Water Pipe", cat: "A", hsn: "73063090", re: new RegExp("chilled water pip", "i"), size: "DIA|MM", spec: "@TRNC|@WINS|@PCOA", free3: "" },
  { code: "CWPP", name: "Condenser Water Pipe", cat: "A", hsn: "73063090", re: new RegExp("condenser water pip", "i"), size: "DIA|MM", spec: "@PCOA!|@WINS!", free3: "" },
  { code: "CNDP", name: "Condensate Drain Pipe", cat: "A", hsn: "39172310", re: new RegExp("condensate drain pipe\\b", "i"), size: "DIA|MM", spec: "FIX:WINS", free3: "" },
  { code: "DRNP", name: "Drain Piping", cat: "A", hsn: "39172310", re: new RegExp("condensate drain piping|drain piping|pvc drain pipe|drain pipe", "i"), size: "DIA|MM", spec: "@UPVC|@NITR", free3: "" },
  { code: "COPP", name: "Copper Pipe", cat: "A", hsn: "74111000", re: new RegExp("copper (refrigerant )?pip|soft drawn copper|refrigerant piping", "i"), size: "DIA|MM", spec: "@WINS", free3: "" },
  { code: "RFNJ", name: "Refnet Joint", cat: "A", hsn: "74111000", re: new RegExp("refn(e|u)t", "i"), size: "NONE", spec: "@WINS", free3: "" },
  { code: "MSPX", name: "MS Pipe", cat: "A", hsn: "73063090", re: new RegExp("ms .?c.? class pipe|m\\.s\\. pipe|ms pipe", "i"), size: "DIA|MM", spec: "ATTR", free3: "" },
  { code: "MBTV", name: "Motorized Butterfly Valve", cat: "A", hsn: "84818090", re: new RegExp("motori[sz]ed butterfly", "i"), size: "DIA|MM", spec: "@WINS|@PN16", free3: "" },
  { code: "BTLV", name: "Butterfly Valve", cat: "A", hsn: "84818030", re: new RegExp("butterfly valve", "i"), size: "DIA|MM", spec: "@WINS|@PN16", free3: "" },
  { code: "MBLV", name: "Manual Balancing Valve", cat: "A", hsn: "84818030", re: new RegExp("(manual )?balancing valve", "i"), size: "DIA|MM", spec: "@WINS|@PN16", free3: "" },
  { code: "BVST", name: "Ball Valve with Strainer", cat: "A", hsn: "84818030", re: new RegExp("ball valve with strainer", "i"), size: "DIA|MM", spec: "@WINS|@PN16", free3: "" },
  { code: "BALV", name: "Ball Valve", cat: "A", hsn: "84811000", re: new RegExp("\\bbal+ valve", "i"), size: "DIA|MM", spec: "@WINS|@PN25|@PN16", free3: "" },
  { code: "2WMV", name: "2-Way Motorized Valve", cat: "A", hsn: "84818090", re: new RegExp("2 ?-?way motori[sz]ed|two way motori", "i"), size: "DIA|MM", spec: "@WINS|@PN16", free3: "" },
  { code: "PICV", name: "Pressure Independent Control Valve", cat: "A", hsn: "84818090", re: new RegExp("pressure independent|picv|dynamic balanc", "i"), size: "DIA|MM", spec: "@WINS|@PN16", free3: "" },
  { code: "YSTR", name: "Y-Strainer", cat: "A", hsn: "84818010", re: new RegExp("strainer", "i"), size: "DIA|MM", spec: "@WINS|@PN16", free3: "" },
  { code: "NRVV", name: "Non Return Valve", cat: "A", hsn: "84818090", re: new RegExp("non[ -]?return valve|\\bnrv\\b", "i"), size: "DIA|MM", spec: "@WINS|@PN16", free3: "" },
  { code: "DRNV", name: "Drain Valve", cat: "A", hsn: "84819090", re: new RegExp("drain valves?", "i"), size: "DIA|MM", spec: "@WINS|@PN16", free3: "" },
  { code: "AAVT", name: "Automatic Air Vent", cat: "A", hsn: "84819090", re: new RegExp("air vent", "i"), size: "DIA|MM", spec: "@WINS|@PN10", free3: "" },
  { code: "APVL", name: "Air Purge Valve", cat: "A", hsn: "84819090", re: new RegExp("air purge", "i"), size: "NONE", spec: "NONE", free3: "" },
  { code: "FRBD", name: "Flexible Rubber Bellows Double Arch", cat: "A", hsn: "40094200", re: new RegExp("rubber bellow|bellows|flexible (rubber )?connector", "i"), size: "DIA|MM", spec: "@WINS|@PN16", free3: "" },
  { code: "ARSP", name: "Air Separator", cat: "A", hsn: "73090090", re: new RegExp("air (& dirt )?separator|dirt separator", "i"), size: "DIA|MM", spec: "@PN10|@PN16", free3: "" },
  { code: "PMST", name: "Pressure Maintaining Station", cat: "A", hsn: "84818030", re: new RegExp("pressure maintaining", "i"), size: "LITRE", spec: "NONE", free3: "" },
  { code: "ACDS", name: "Automatic Chemical Dosing System", cat: "A", hsn: "", re: new RegExp("chemical dosing", "i"), size: "NONE", spec: "NONE", free3: "" },
  { code: "DRTR", name: "Insulated Drain Drip Tray", cat: "A", hsn: "73089090", re: new RegExp("drip tray", "i"), size: "GAUGE", spec: "NONE", free3: "" },
  { code: "DRPM", name: "Drain Pump", cat: "A", hsn: "84137010", re: new RegExp("drain pump", "i"), size: "NONE", spec: "NONE", free3: "" },
  { code: "CETM", name: "Cable End Termination", cat: "A", hsn: "85369090", re: new RegExp("cable end termination", "i"), size: "NONE", spec: "NONE", free3: "" },
  { code: "CCBL", name: "Control Cable", cat: "A", hsn: "85446090", re: new RegExp("control cable", "i"), size: "NONE", spec: "NONE", free3: "" },
  { code: "TRCV", name: "Cable Tray Cover", cat: "A", hsn: "73089090", re: new RegExp("solid cover", "i"), size: "WIDTH", spec: "NONE", free3: "" },
  { code: "LCTY", name: "Ladder Cable Tray", cat: "A", hsn: "73262090", re: new RegExp("ladder type|ladder cable tray", "i"), size: "WXD|WIDTH", spec: "TTHK", free3: "" },
  { code: "CTRY", name: "Cable Tray", cat: "A", hsn: "72169930", re: new RegExp("cables? trays?|perforated (type )?cable tray|gi tray|g\\.i\\. tray", "i"), size: "WIDTH", spec: "@ALPC|@HDGL", free3: "" },
  { code: "GIXX", name: "GI Conduit", cat: "A", hsn: "73069090", re: new RegExp("gi conduit", "i"), size: "FIX:COND", spec: "DIA|MM", free3: "" },
  { code: "PVCC", name: "PVC Conduit", cat: "A", hsn: "39172390", re: new RegExp("pvc conduit", "i"), size: "DIA|MM", spec: "NONE", free3: "" },
  { code: "MSCD", name: "MS Conduit", cat: "A", hsn: "73069090", re: new RegExp("conduit", "i"), size: "DIA|MM", spec: "NONE", free3: "" },
  { code: "GIST", name: "GI Strip", cat: "A", hsn: "72172010", re: new RegExp("g\\.?i\\.?\\s*strip|mm width g\\.?i|earthing strip", "i"), size: "STRIP", spec: "FIX:ERTH", free3: "" },
  { code: "CUWR", name: "Copper Earthing Wire", cat: "A", hsn: "74081990", re: new RegExp("\\bcu wire|copper wire", "i"), size: "SWG", spec: "FIX:ERTH", free3: "" },
  { code: "GIWR", name: "GI Wire", cat: "A", hsn: "72172010", re: new RegExp("gi wires?|\\d\\s*swg\\b", "i"), size: "SWG", spec: "FIX:ERTH", free3: "" },
  { code: "STND", name: "Outdoor Unit Stand", cat: "A", hsn: "72161000", re: new RegExp("outdoor unit stand|odu stand|iron stand", "i"), size: "FIX:ODUX", spec: "FIX:IRON", free3: "" },
  { code: "CABL", name: "Cable", cat: "A", hsn: "85446090", re: new RegExp("cable|wiring", "i"), size: "CABLE", spec: "ATTR", free3: "" },
  { code: "MSDC", name: "MS Duct", cat: "D", hsn: "73089090", re: new RegExp("\\bms duct(ing)?(?!\\s*(fire wrap|access))", "i"), size: "GAUGE", spec: "FIX:FRTD", free3: "" },
  { code: "RGSD", name: "Round GSS Duct", cat: "D", hsn: "73089090", re: new RegExp("round (gss )?duct|spiral round duct", "i"), size: "GAUGE", spec: "FIX:SSKN", free3: "" },
  { code: "FODC", name: "Flat Oval Duct", cat: "D", hsn: "73089090", re: new RegExp("flat oval (gi )?duct|ell?iptical duct|flat oval spiral", "i"), size: "GAUGE", spec: "FIX:SSKN", free3: "" },
  { code: "GSSD", name: "GSS Ducting", cat: "D", hsn: "73089090", re: new RegExp("g\\.?s\\.?s\\.? duct|rectangular (gi )?ducts?|boxed ducts|sheet metal work", "i"), size: "GAUGE", spec: "@FRTD|@STPX", free3: "" },
  { code: "INSU", name: "Insulation", cat: "A", hsn: "40091100", re: new RegExp("insulation", "i"), size: "THK", spec: "ATTR", free3: "" },
];

export const MISC_CODE = "MISC";
