import { notFound } from "next/navigation";
import { asc, eq } from "drizzle-orm";
import { db, schema as S } from "@/db";
import { requireUser } from "@/lib/auth";
import { fmtDate, inr, quoteTotals } from "@/lib/format";

export const metadata = { title: "Quotation" };

export default async function PrintQuote(props: PageProps<"/quotations/[id]/print">) {
  await requireUser();
  const { id } = await props.params;
  const q = await db.query.quotations.findFirst({ where: eq(S.quotations.id, id) });
  if (!q) notFound();
  const o = (await db.query.opportunities.findFirst({ where: eq(S.opportunities.id, q.opportunityId) }))!;
  const a = await db.query.accounts.findFirst({ where: eq(S.accounts.id, o.accountId) });
  const c = await db.query.contacts.findFirst({ where: eq(S.contacts.accountId, o.accountId) });
  const owner = o.ownerId ? await db.query.users.findFirst({ where: eq(S.users.id, o.ownerId) }) : null;
  const items = await db.select().from(S.quoteItems).where(eq(S.quoteItems.quotationId, id)).orderBy(asc(S.quoteItems.sort));
  const t = quoteTotals(items, q.discountPct, q.gstPct);
  return (
    <main className="mx-auto flex max-w-[820px] flex-col gap-6 bg-white p-10 text-[13px] text-[#13222b] [color-scheme:light]">
      <header className="flex items-start justify-between border-b-2 border-[#0a6f8c] pb-4">
        <div>
          <div className="h-display text-[26px] tracking-[0.04em]" style={{ fontStretch: "80%" }}>SPACE<span className="text-[#0a6f8c]">AIR</span></div>
          <div className="text-xs text-[#6b7c85]">MEP Contracting · HVAC · Fire · Electrical · Plumbing<br />Chennai · Bangalore · Hyderabad · Renigunta · Colombo</div>
        </div>
        <div className="text-right">
          <div className="h-display text-[18px]">QUOTATION</div>
          <div className="font-mono text-xs">{q.code} R{q.revision}</div>
          <div className="text-xs">Date {fmtDate(q.sentAt ?? q.createdAt)} · valid {q.validityDays} days</div>
        </div>
      </header>
      <section className="grid grid-cols-2 gap-6">
        <div><div className="text-[11px] font-semibold uppercase tracking-wider text-[#6b7c85]">To</div><b>{a?.name}</b><br />{c?.name}, {c?.role}<br />{a?.city}</div>
        <div><div className="text-[11px] font-semibold uppercase tracking-wider text-[#6b7c85]">Subject</div>{o.title}</div>
      </section>
      <table className="w-full border-collapse">
        <thead><tr className="bg-[#e7edec] text-left text-[11px] uppercase tracking-wider"><th className="p-2">#</th><th className="p-2">Description</th><th className="p-2">Unit</th><th className="p-2 text-right">Qty</th><th className="p-2 text-right">Rate</th><th className="p-2 text-right">Amount</th></tr></thead>
        <tbody>{items.map((i, n) => <tr key={i.id} className="border-b border-[#d3dcdb]"><td className="p-2">{n + 1}</td><td className="p-2">{i.description}</td><td className="p-2">{i.unit}</td><td className="p-2 text-right">{i.qty.toLocaleString("en-IN")}</td><td className="p-2 text-right font-mono">{inr(i.rate)}</td><td className="p-2 text-right font-mono">{inr(i.qty * i.rate)}</td></tr>)}</tbody>
      </table>
      <dl className="ml-auto grid w-72 grid-cols-[1fr_auto] gap-1">
        <dt>Basic value</dt><dd className="text-right font-mono">{inr(t.basic)}</dd>
        {q.discountPct > 0 && (<><dt>Discount {q.discountPct}%</dt><dd className="text-right font-mono">− {inr(t.discount)}</dd></>)}
        <dt>GST {q.gstPct}%</dt><dd className="text-right font-mono">{inr(t.gst)}</dd>
        <dt className="font-bold">Total</dt><dd className="text-right font-mono font-bold">{inr(t.total)}</dd>
      </dl>
      <section><div className="text-[11px] font-semibold uppercase tracking-wider text-[#6b7c85]">Terms</div>{q.terms}</section>
      <footer className="mt-6 flex justify-between border-t border-[#d3dcdb] pt-4 text-xs">
        <div>For SPACEAIR<br /><br /><b>{owner?.name}</b><br />{owner?.title} · {owner?.phone}</div>
        <div className="self-end text-[#6b7c85]">Generated by Spaceair CRM</div>
      </footer>
    </main>
  );
}
